POST /instore/_mapping/taskitem/
{
 "taskitem":{
            "properties":{
               "@timestamp":{
                  "type":"date",
                  "format":"dateOptionalTime"
               },
               "@version":{
                  "type":"string"
               },
               "_internalId":{
                  "type":"string"
               },
               "actionId":{
                  "type":"long"
               },
               "actionText":{
                  "type":"string"
               },
               "agentHost":{
                  "type":"string"
               },
               "agentTimestamp":{
                  "type":"string"
               },
               "application_version":{
                  "type":"string"
               },
               "chainId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "chainName":{
                  "type":"string"
               },
               "companyId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "companyName":{
                  "type":"string"
               },
               "createDate":{
                  "type":"date",
                  "format":"dateOptionalTime"
               },
               "eRPPrice":{
                  "type":"double"
               },
               "expectedQuantity":{
                  "type":"double"
               },
               "hierarchicalId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "hierarchicalName":{
                  "type":"string"
               },
               "hierarchicalDPTName":{
                  "type":"string"
               },
               "host":{
                  "type":"string"
               },
               "isIncrease":{
                  "type":"long"
               },
               "isItemGroupOriented":{
                  "type":"boolean"
               },
               "isPriceDivergence":{
                  "type":"boolean"
               },
               "itemId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "itemName":{
                  "type":"string"
               },
               "labelPrice":{
                  "type":"double"
               },
               "lastUpdateDate":{
                  "type":"date",
                  "format":"dateOptionalTime"
               },
               "lastUpdateUser":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "lastUpdateUserName":{
                  "type":"string"
               },
               "level":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "message":{
                  "type":"string"
               },
               "metric":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "oldERPPrice":{
                  "type":"double"
               },
               "pOSPrice":{
                  "type":"double"
               },
               "priceDivergenceDescriptionKey":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "priceOwner":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "product":{
                  "type":"string"
               },
               "quantity":{
                  "type":"double"
               },
               "retailGroupId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "retailGroupName":{
                  "type":"string"
               },
               "retailStoreId":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "retailStoreName":{
                  "type":"string"
               },
               "status":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "stockDescriptionKey":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "tags":{
                  "type":"string"
               },
               "taskId":{
                  "type":"long"
               },
               "taskItemId":{
                  "type":"long"
               },
               "taskName":{
                  "type":"string"
               },
               "taskStatus":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "taskStatusDescriptionKey":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "taskItemStatusKey":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "taskItemStatusDescriptionKey":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "thread":{
                  "type":"string"
               },
               "type":{
                  "type":"string",
                  "index":"not_analyzed"
               },
                "cycleCountDesc":{
                  "type":"string"
               },
                "countZone":{
                  "type":"string",
                  "index":"not_analyzed"
               },
               "countZoneDesc":{
                  "type":"string"
               },
                "alertId":{
                  "type":"long"
               },
                "cycleCount":{
                  "type":"long"
               }
            }
         }
}